[package]
name = "captcha_breaker"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
lapjv = "0.2.1"
ndarray = "0.16.1"
once_cell = "1.21.3"
ort = { version = "=2.0.0-rc.9" }
reqwest = {version = "0.12.15", features = ["blocking"]}
toml = "0.8.20"

[features]
default = ["chinese_click_0"]
cuda = ["ort/cuda"]
chinese_click_0 = ["_model_yolo11n" ]


_model_yolo11n = []
